name: human_selection
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - numpy
  - scipy
  - matplotlib
  - seaborn
  - openpyxl
  - xlrd
  - pip
  - pip:
    - gseapy
